[project]
name = "chat-demo-clients"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "awscli-local>=0.22.2",
    "boto3>=1.43.74",
    "dotenv>=0.9.9",
    "google-genai>=2.18.1",
    "pandas>=3.0.5",
    "pathlib>=1.0.1",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.15.0",
    "python-dotenv>=1.2.3",
    "streamlit>=1.61.1",
]
